### ISSUE TITLE
Add build status to README

### ISSUE THREAD

**Issue by kbaum** [viewthespace/finance#2]
Tried running tests on ruby 2.3.1 and they seem to be failing:

```
# Running:

EE......FEEEEEEF................................

Finished in 1.629714s, 29.4530 runs/s, 465.7258 assertions/s.

  1) Error:
Numeric Method#test_0001_works with simple invocation:
NoMethodError: undefined method `amortize' for 300000:Fixnum
    /Users/kb/workspace/finance/test/test_amortization.rb:153:in `block (2 levels) in <top (required)>'


  2) Error:
Numeric Method#test_0002_works with block invocation:
NoMethodError: undefined method `amortize' for 300000:Fixnum
    /Users/kb/workspace/finance/test/test_amortization.rb:160:in `block (2 levels) in <top (required)>'


  3) Failure:
Cashflows::guess #test_0003_should not allow non-numeric guesses [/Users/kb/workspace/finance/test/test_cashflows.rb:49]:
[ArgumentError] exception expected, not
Class: <NoMethodError>
Message: <"undefined method `xirr' for [Transaction(-1000), Transaction(390000)]:Array">
---Backtrace---
/Users/kb/workspace/finance/test/test_cashflows.rb:49:in `block (4 levels) in <top (required)>'
---------------


  4) Error:
Cashflows::guess #test_0002_should calculate correct rate with new guess (0.1):
NoMethodError: undefined method `xirr' for [Transaction(-1000), Transaction(390000)]:Array
    /Users/kb/workspace/finance/test/test_cashflows.rb:45:in `block (3 levels) in <top (required)>'


  5) Error:
Cashflows::guess #test_0001_should fail to calculate with default guess (1.0):
NoMethodError: undefined method `xirr' for [Transaction(-1000), Transaction(390000)]:Array
    /Users/kb/workspace/finance/test/test_cashflows.rb:41:in `block (3 levels) in <top (required)>'


  6) Error:
Cashflows::an array of Transactions#test_0001_should have an Internal Rate of Return:
NoMethodError: undefined method `xirr' for [Transaction(-1000), Transaction(600), Transaction(600)]:Array
    /Users/kb/workspace/finance/test/test_cashflows.rb:24:in `block (3 levels) in <top (required)>'


  7) Error:
Cashflows::an array of Transactions#test_0002_should have a Net Present Value:
NoMethodError: undefined method `xnpv' for [Transaction(-1000), Transaction(600), Transaction(600)]:Array
    /Users/kb/workspace/finance/test/test_cashflows.rb:29:in `block (3 levels) in <top (required)>'


  8) Error:
Cashflows::an array of numeric cashflows#test_0001_should have an Internal Rate of Return:
NoMethodError: undefined method `irr' for [-4000, 1200, 1410, 1875, 1050]:Array
    /Users/kb/workspace/finance/test/test_cashflows.rb:6:in `block (3 levels) in <top (required)>'


  9) Error:
Cashflows::an array of numeric cashflows#test_0002_should have a Net Present Value:
NoMethodError: undefined method `npv' for [-100.0, 60, 60, 60]:Array
    /Users/kb/workspace/finance/test/test_cashflows.rb:11:in `block (3 levels) in <top (required)>'


 10) Failure:
Cashflows::default values#test_0001_should have default values [/Users/kb/workspace/finance/test/test_config.rb:7]:
Expected: DecNum('1.0')
  Actual: DecNum('0.25')

```

**Comment by kbaum** [comment]
fails also on ruby-2.2.5.
